name: flanders
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ./Flare-Flutter/flare_flutter

  latlong: 0.6.1
  location: ^1.4.1
  google_maps_flutter: ^0.3.0+2
  cloud_firestore: 0.8.2+3

  geoflutterfire:

  #  firebase_auth:

  provider:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
   - assets/avatars/

