name: flanders
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong: 0.6.1
  firebase_auth: 0.7.0
  cloud_firestore: 0.8.2+3
  google_sign_in: 3.2.4
  rxdart:


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/avatars/

